### ISSUE TITLE
Add a `write` method to a MidiFile object

### ISSUE THREAD

**Issue by WojciechMat** [Nospoko/fortepyan#11]
## Desired functionality
I want to be able to save a midi file to a desired filepath using a simple MidiFile functionality, like:

```py
import fortepyan as ff

midi_file = ff.MidiFile("my_midi_file.mid")
midi_file.write("copy_of_my_midi_file.mid")
```

**Comment by roszcz** [comment]
@WojciechMat version 0.4.2 already enabled writing of `MidiFile` objects to midi files: https://github.com/Nospoko/fortepyan/blob/develop/fortepyan/midi/structures.py#L585
